.TH STRING_CONCATB 3  2008-10-28 "http://github.com/hce/bstring" "bstring user's manual"
.SH NAME
string_concatb - append to a bstring
.SH SYNOPSIS
.nf
.B #include <bstring.h>
.sp
.BI "int string_concatb(string* " string ", const char* " src ", uintptr_t " len ");
.sp
.SH DESCRIPTION
The
.BR string_concatb()
adds \fBlen\fP bytes at \fBsrc\fP to \fBstring\fP.
.SH NOTES
If \fBlen\fP bytes do not fit into the internal buffer, that buffer is
resized by a multiple of the \fBgrow\fP value specified at string
creation.
.PP
Since memory allocation can fail, a call to
.BR string_concatb()
can fail;
in that case, \fBstring\fP is still valid and in the state it was in
before the call to \fBstring_concatb()\fP.
.SH RETURN VALUE
.BR string_concatb()
returns 0 on success, otherwise a nonzero value.
.SH SEE ALSO
.BR string_init (3)
.BR string_concat (3)
